### PR TITLE
[FEA] Swap out `ccache` for `sccache`

### PR DESCRIPTION
**Pull request by trxcllnt**
Swaps out `ccache` for `sccache`, allowing us to share the common build cache via something like AWS S3 or GCP.

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]
nice! will this require us to manage/distribute AWS credentials to node-rapids users?

**Review by mzegar — APPROVED** [review]
Really cool stuff, didn't find anything on my end.

**Review by AjayThorve — APPROVED** [review]
LGTM!!! yay for shareable build caches!!

**Review by bryevdv — APPROVED** [review]

**Review by love-lena — APPROVED** [review]
No problems in the parts I have context on.
I would like to hear more about the AWS implementation but it looks like sccache is set up to default to a local cache if no creds are provided, so shouldn't be a problem

**Pull request merged**
